apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: leave-nginx-deployment
  namespace: tan-app
  labels:
    env: dev
  annotations: #used to attach data
    scaleDown: '0'
    scaleUp: '1'
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: leave-nginx
    spec:
      containers:
        - name: leave-nginx
          image: docker.io/ebenezer/leave-nginx:v3
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 400Mi
            requests:
              cpu: 50m
              memory: 200Mi
          volumeMounts:
            - name: default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: js
              mountPath: /var/www/static/bootstrap/js/bootstrap.min.js
              subPath: bootstrap.min.js
            - name: css
              mountPath: /var/www/static/bootstrap/css/bootstrap.min.css
              subPath: bootstrap.min.css
      volumes:
        #   consume the file-like keys of the configmap via volume plugin
          - name: default-conf
            configMap:
              name: default.conf
              items:
              - key: default.conf
                path: default.conf
          - name: js
            configMap:
              name: bootstrap.min.js
              items:
              - key: bootstrap.min.js
                path: bootstrap.min.js
          - name: css
            configMap:
              name: bootstrap.min.css
              items:
              - key: bootstrap.min.css
                path: bootstrap.min.css

          
